# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-12 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('fool', '允許搞'),)},
        ),
    ]
