# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
