# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name_plural': '圖片'},
        ),
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='', verbose_name='圖片路徑'),
        ),
        migrations.AlterField(
            model_name='img',
            name='summary',
            field=models.CharField(max_length=128, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(max_length=16, verbose_name='標題'),
        ),
    ]
