# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用戶'), (1, '超級用戶'), (2, 'VIP')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='請輸入全英文用戶名', max_length=32, verbose_name='用戶名'),
        ),
    ]
