# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_part_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=32),
            preserve_default=False,
        ),
    ]
