# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-14 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Staff2ToTag2',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ctime', models.DateField()),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Staff2')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('staf', models.ManyToManyField(to='app01.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='staff2totag2',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag2'),
        ),
    ]
