# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名稱')),
            ],
            options={
                'verbose_name_plural': '分類(視頻分類)',
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名稱')),
                ('classification', models.ManyToManyField(to='app01.Classification')),
            ],
            options={
                'verbose_name_plural': '方向(視頻方向)',
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '難度級別',
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下線'), (1, '上線')], default=1, verbose_name='狀態')),
                ('weight', models.IntegerField(default=0, verbose_name='權重')),
                ('title', models.CharField(max_length=32, verbose_name='標題')),
                ('summary', models.CharField(max_length=32, verbose_name='簡介')),
                ('img', models.CharField(max_length=32, verbose_name='圖片')),
                ('href', models.CharField(max_length=256, verbose_name='視頻地址')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Classification')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Level')),
            ],
            options={
                'verbose_name_plural': '視頻',
                'db_table': 'Video',
            },
        ),
    ]
