# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '下線'), (2, '上線')], default=1, verbose_name='狀態'),
        ),
    ]
