# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-07 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='ct',
            field=models.ManyToManyField(related_name='classes_set', to='app01.Teachers'),
        ),
    ]
