# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, '未處理'), (2, '處理中'), (3, '已處理')], default=1)),
                ('solution', models.TextField(blank=True, null=True)),
                ('solution_time', models.DateTimeField()),
                ('pj', models.IntegerField(blank=True, choices=[(1, '不滿意'), (2, '一般'), (3, '粉滿意')], default=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='頭像'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='repository.UserInfo'),
        ),
    ]
