# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181204_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='solution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
